"""Update relationship one role many auditions

Revision ID: e1dce1bd49fb
Revises: 93c428521c82
Create Date: 2023-04-04 12:36:13.774360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1dce1bd49fb'
down_revision = '93c428521c82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_auditions_role_id_roles'), 'auditions', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_auditions_role_id_roles'), 'auditions', type_='foreignkey')
    # ### end Alembic commands ###
